[build]
  publish = "."  # since you're serving files from root
  functions = "netlify/functions"

# Serve index.html for all account routes
[[redirects]]
from = "/kagio"
to = "/index.html"
status = 200

[[redirects]]
from = "/kianyaga"
to = "/index.html"
status = 200

[[redirects]]
from = "/aievo"
to = "/index.html"
status = 200

[[redirects]]
from = "/kerugoya"
to = "/index.html"
status = 200

# Fallback for root
[[redirects]]
from = "/"
to = "/index.html"
status = 200

# === ASSET CACHING ===
[[headers]]
  for = "/Assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"  # 1 year cache
    Access-Control-Allow-Origin = "*"